<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "link".
 *
 * @property int $id ID
 * @property string $title 标题
 * @property string $url 路径
 * @property int $created_at 创建时间
 * @property int $status 状态
 */
class Link extends \yii\db\ActiveRecord
{


    //场景

    const SCENARIO_ADMIN_CREATE='2';//后台管理员新增
    const SCENARIO_ADMIN_UPDATE='3';//后台管理员更新
    const SCENARIO_JQ_UPLOAD='4';//JQ上传场景
    public $file;

    public $verifyCode;

    const STATUS_ARRAY=['停用','启用'];
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'link';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['created_at', 'pic_id', 'status'], 'integer'],
            [['title', 'url'], 'string', 'max' => 255],
            [ 'verifyCode', 'captcha'],// 这里的'captcha'是系统的关键字，不能写成其他
            UploadImg::rules('file',['maxSize' => 3000000,'skipOnEmpty'=>true,'minWidth'=>900,'minHeight'=>600]),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'ID'),
            'title' => Yii::t('backend', '标题'),
            'url' => Yii::t('backend', '路径'),
            'created_at' => Yii::t('backend', '创建时间'),
            'status' => Yii::t('backend', '状态'),
            'pic_id' => Yii::t('backend', 'PIC ID'),
            'verifyCode' => '验证码', //验证码的名称，根据个人喜好设定
        ];
    }


    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        $scenarios=parent::scenarios(); // TODO: Change the autogenerated stub


        //后台场景
        $scenarios[self::SCENARIO_ADMIN_CREATE]=[
            'bs_id','file'
        ];
        $scenarios[self::SCENARIO_ADMIN_UPDATE]=[
            'bs_id', 'pic_id','file'
        ];
        //JQ上传
        $scenarios[self::SCENARIO_JQ_UPLOAD]=[
             'pic_id'
        ];
        return $scenarios;
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPic()
    {
        return $this->hasOne(Pic2::className(), ['id' => 'pic_id']);
    }

}
