<?php

namespace backend\models;

use common\components\Aliyunoss;
use Yii;

/**
 * This is the model class for table "alioss".
 *
 * @property int $id id
 * @property string $path 路径
 */
class Alioss extends \yii\db\ActiveRecord
{
    public $files;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'alioss';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['path'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'id'),
            'path' => Yii::t('backend', '路径'),
            'files' => Yii::t('backend', '文件'),
        ];
    }
    public function afterDelete()
    {
        if($this->path){
            $oss=new Aliyunoss();
            $oss->delete($this->path);
        }

        parent::afterDelete(); // TODO: Change the autogenerated stub
    }
}
