<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "task".
 *
 * @property int $id id
 * @property string $describe 描述
 * @property int $status 状态
 * @property int $created_at 添加时间
 */
class Task extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'task';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['status', 'created_at'], 'integer'],
            [['describe'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('backend', 'id'),
            'describe' => Yii::t('backend', '描述'),
            'status' => Yii::t('backend', '状态'),
            'created_at' => Yii::t('backend', '添加时间'),
        ];
    }





    public function beforeSave($insert)
    {
        $this->created_at=time();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
